python -u main.py --dataset assist2009_updated --train_set 1
python -u main.py --dataset assist2009_updated --train_set 2
python -u main.py --dataset assist2009_updated --train_set 3
python -u main.py --dataset assist2009_updated --train_set 4
python -u main.py --dataset assist2009_updated --train_set 5
python -u main.py --dataset assist2015 --train_set 1
python -u main.py --dataset assist2015 --train_set 2
python -u main.py --dataset assist2015 --train_set 3
python -u main.py --dataset assist2015 --train_set 4
python -u main.py --dataset assist2015 --train_set 5
python -u main.py --dataset assist2017 --train_set 1
python -u main.py --dataset assist2017 --train_set 2
python -u main.py --dataset assist2017 --train_set 3
python -u main.py --dataset assist2017 --train_set 4
python -u main.py --dataset assist2017 --train_set 5
python -u main.py --dataset STATICS --train_set 1
python -u main.py --dataset STATICS --train_set 2
python -u main.py --dataset STATICS --train_set 3
python -u main.py --dataset STATICS --train_set 4
python -u main.py --dataset STATICS --train_set 5
python -u main.py --dataset synthetic --train_set 1
python -u main.py --dataset synthetic --train_set 2
python -u main.py --dataset synthetic --train_set 3
python -u main.py --dataset synthetic --train_set 4
python -u main.py --dataset synthetic --train_set 5
